### ISSUE TITLE
Feature request: put on CRAN

### ISSUE THREAD

**Issue by richelbilderbeek** [jtextor/epitope-prediction#2]
Hi @jtextor,

Thanks for this great package! Because I would enjoy other people to be able to find it as well, putting it on CRAN would help.

Do you have any plans to get this package if CRAN? If no, what if I volunteered to do so?

Cheers, Richel

**Comment by jtextor** [comment]
This package cannot be put on CRAN due to its relatively restrictive license. See README.md for explanation.
